In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.multioutput import MultiOutputRegressor

In [3]:
df=pd.read_csv('patient_recovery_data.csv')
df.head()

   Age   BMI  ...  Recovery_Days  Pain_Reduction_Score
0   58  35.5  ...           67.2                   0.0
1   71  19.2  ...           44.7                   7.7
2   48  39.7  ...           77.4                   0.0
3   34  34.9  ...           98.7                   0.0
4   62  22.0  ...           64.6                   0.0

[5 rows x 8 columns]

In [4]:
df.describe()

              Age         BMI  ...  Recovery_Days  Pain_Reduction_Score
count  120.000000  120.000000  ...     120.000000            120.000000
mean    50.850000   28.394167  ...      69.301667              1.687500
std     17.971336    6.627550  ...      19.155055              4.147401
min     21.000000   17.600000  ...      20.000000              0.000000
25%     35.750000   22.750000  ...      58.150000              0.000000
50%     48.500000   28.650000  ...      67.700000              0.000000
75%     66.000000   34.525000  ...      83.825000              0.000000
max     79.000000   39.700000  ...     113.500000             19.100000

[8 rows x 8 columns]

In [5]:
# Check missing values
print('Missing values per column:')
print(df.isnull().sum())

Missing values per column:
Age                     0
BMI                     0
Blood_Pressure          5
Therapy_Hours           0
Medication_Dosage       5
Preexisting_Score       0
Recovery_Days           0
Pain_Reduction_Score    0
dtype: int64

In [6]:
# Fill missing values with column mean
df.fillna(df.mean(), inplace=True)
print('✅ Missing values filled with mean.')
print('Remaining missing values:', df.isnull().sum().sum())

✅ Missing values filled with mean.
Remaining missing values: 0

In [7]:
features = ['Age', 'BMI', 'Blood_Pressure', 'Therapy_Hours', 'Medication_Dosage', 'Preexisting_Score']
X = df[features]
y = df[['Recovery_Days', 'Pain_Reduction_Score']]

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.head()

     Age   BMI  ...  Medication_Dosage  Preexisting_Score
42    34  19.2  ...          13.100000                  5
12    30  20.1  ...          35.300000                  6
15    55  24.9  ...          59.500000                  4
114   79  20.1  ...          54.456522                  8
76    33  24.3  ...          55.100000                  9

[5 rows x 6 columns]

In [10]:
X_test.head()

    Age   BMI  ...  Medication_Dosage  Preexisting_Score
44   70  21.1  ...               40.6                  2
47   71  31.8  ...               95.0                  5
4    62  22.0  ...               53.0                  5
55   58  24.7  ...               91.1                  2
26   21  30.1  ...               10.5                  2

[5 rows x 6 columns]

In [11]:
# Compute mean from training data only
train_means = X_train.mean()

# Apply to both sets
X_train = X_train.fillna(train_means)
X_test  = X_test.fillna(train_means)

In [13]:
# Write your code here
base_model = LinearRegression()
model = MultiOutputRegressor(base_model)

model.fit(X_train, y_train)

MultiOutputRegressor(estimator=LinearRegression())

In [14]:
y_pred = model.predict(X_test)
print(y_pred)

[[ 5.17210208e+01  4.21482679e+00]
 [ 7.97624431e+01  2.67387512e+00]
 [ 6.70583168e+01  1.38650265e+00]
 [ 7.62360477e+01  1.20975828e+00]
 [ 4.58244746e+01  4.22557079e+00]
 [ 6.07747104e+01  2.90682821e+00]
 [ 5.24118172e+01  8.25178095e+00]
 [ 4.84430998e+01  3.85286916e+00]
 [ 1.14133324e+02 -4.45048371e+00]
 [ 5.76023766e+01  4.24286552e+00]
 [ 3.64171047e+01  5.99000845e+00]
 [ 7.30717156e+01  6.79471918e-01]
 [ 5.22198994e+01  2.45403029e+00]
 [ 4.20569382e+01  5.88710565e+00]
 [ 6.43020316e+01  2.42822412e+00]
 [ 8.62912679e+01 -1.08061305e+00]
 [ 9.60409000e+01 -2.22554996e+00]
 [ 6.88404919e+01  4.42267249e+00]
 [ 3.38345309e+01  6.30101735e+00]
 [ 4.38040618e+01  4.53280774e+00]
 [ 6.09575354e+01  2.93820902e+00]
 [ 9.14550864e+01 -8.82386395e-01]
 [ 6.57091085e+01 -3.63494063e-02]
 [ 9.68504437e+01 -2.86619156e+00]]

In [17]:
mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')

Mean Absolute Error: 3.4167978444409064

In [18]:
rmse = mean_squared_error(y_test, y_pred)
print(f'Root Mean Squared Error: {rmse}')

srmse= np.sqrt(mean_squared_error(y_test, y_pred))
print(f'Square Root Mean Squared Error: {srmse}')

Root Mean Squared Error: 21.56378732352362
Square Root Mean Squared Error: 4.643682517520294

In [19]:
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')

R-squared: 0.6185729724861786